version: 2
jobs:
  working_directory: /app
  docker:
    - image: docker:17.05.0-ce-git
  steps:
    - checkout
    - setup_remote_docker
    - run:
        TAG=`date +%Y.%m.%d`
        git tag $TAG
        git push origin $TAG
